### ISSUE TITLE
Create datagrid Table

### ISSUE THREAD

**Issue by jarancibiaby** [jarancibiaby/housy-host-admin#1]
Tabla (datagrid) con pocas columnas que tenga los datos (3/4 columnas por default). Este componente de Datagrid te deja seleccionar que columnas ver y cuales no. También te deja filtrar los datos.

>Las columnas por default son: Inmueble, Mes, Id_reserva

Columnas que se muestran: 
 
![image](https://user-images.githubusercontent.com/126164481/220907081-33848549-0cc5-4a59-aef0-ead0fc1f173a.png)
![image](https://user-images.githubusercontent.com/126164481/220907091-ed35b33d-cfa3-42be-9300-dfd36cd8e307.png)

**Comment by rodrigo-funes-biasatti** [comment]
Complete in merge: a2509fb380649c714675ea4c61b2149674ddd99b
